### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by hmzgtl16** [kotlin-hands-on/chat-app-websockets#1]
how initialize the project with same the structure of two apps  with out clone it and open it

**Comment by SebastianAigner** [comment]
Hi @Hamza1605 !

The two apps are completely independent from each other, so you can just create two applications using IntelliJ IDEA's project wizard and put them in the same folder, then open this parent folder in IntelliJ IDEA, and work on the projects as you see fit.

Hope this helps!
